#!/bin/bash

# Check if all 4 parameters are passed
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
path_to_file=$1
server_ip=$2
username=$3
path_to_key=$4

# Transfer the file to the user's home directory on the server
scp -i "$path_to_key" -o StrictHostKeyChecking=no "$path_to_file" "$username"@"$server_ip":~/

