#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20

svar=1

while [[ $svar -lt 21 ]];
do
	case $svar in
		4)
			echo $svar
			echo "bad luck from China"
			;;
		8)
			echo $svar
			echo "bad luck from Japan"
			;;
		17)
			echo $svar
			echo "bad luck from Italy"
			;;
		*)
			echo $svar
			;;
	esac
	((svar++))
done
